Salable/node-sdk

package-lock.json
src/types.ts

- Updated IRole and IRbacUser interfaces

fix: updated IRole and IRbacUser interfaces

---

src/licenses/licenses.test.ts
src/rbac/rbac.test.ts

test: rbac

---

src/types.ts

fix: added isTest to the response types

---

src/products/index.ts
src/products/v2/index.ts
src/types.ts

[SD-1065](https://salable.atlassian.net/browse/SD-1065)

feat: product resource with its methods

---

__tests__/_setup/setup-test-envs.ts
jest.config.js
src/index.ts
test-utils/helpers/console-loading-wheel.ts
test-utils/kms/kms-symmetric-encrypt.ts
test-utils/scripts/create-test-data.ts
test-utils/stripe/create-stripe-test-data.ts

- Added create-test-data function to create test data before unit tests

feat: added create-test-data function

---

docs/docs/pricing-tables/_category_.json
docs/docs/pricing-tables/get-one.md

- SD-1197
- Updated pricing tables resource docs

feat: updated pricing table resource docs

---

docs/docs/licenses/check.md
docs/docs/licenses/create-many.md
docs/docs/licenses/create.md
docs/docs/licenses/get-all.md
docs/docs/licenses/get-count.md
docs/docs/licenses/get-for-granteeId.md
docs/docs/licenses/get-for-purchaser.md
docs/docs/licenses/get-one.md
docs/docs/licenses/update-many.md
docs/docs/licenses/update.md
docs/docs/licenses/verify.md
docs/docs/plans/_category_.json
docs/docs/plans/get-capabilities.md
docs/docs/plans/get-checkout-link.md
docs/docs/plans/get-currencies.md
docs/docs/plans/get-features.md
docs/docs/plans/get-one.md
docs/docs/pricing-tables/_category_.json
docs/docs/pricing-tables/get-one.md
src/plans/index.ts
src/types.ts

- SD-1196
- Updated plans resource docs with new method signatures
- Minor changes to the license resource docs

feat: updated plans docs + minor changes to licenses resource

---

docs/docs/changelog.md
src/subscriptions/index.ts

- SD-1201
- Updated change log with v4 update

feat(SD-1201): updated changelog with v4 changes

---

src/licenses/index.ts
src/plans/index.ts
src/types.ts

- Added missing option parameters for plans and license methods

fix: added missing option parameters

---

src/index.ts
src/init-request.test.ts
src/licenses/v2/licenses-v2.test.ts
src/subscriptions/v2/subscriptions-v2.test.ts

refactor: throw SalableRequestError if 404

---

src/exceptions/salable-error.ts
src/index.ts
src/init-request.test.ts

Added ErrorCodes enum to the code property.
Updated some tests to check for correct error codes. 
-

test: fixed broken test

---

docs/docs/licenses/get-all.md
docs/docs/subscriptions/get-all.md
docs/docs/subscriptions/get-invoices.md
src/licenses/v2/licenses-v2.test.ts
src/subscriptions/index.ts
src/subscriptions/v2/subscriptions-v2.test.ts
src/types.ts

fix: changed take to number type. Added pagination to invoices

---

docs/docs/licenses/cancel-many.md

[SD-1389](https://salable.atlassian.net/browse/SD-1389)

docs: update cancel licenses doc to reflect correct allowed params

---

package-lock.json
src/index.ts
src/sessions/index.ts
src/sessions/v2/index.ts
src/sessions/v2/sessions-v2.test.ts
src/types.ts
test-utils/stripe/create-stripe-test-data.ts

[SD-1253](https://salable.atlassian.net/browse/SD-1253)

feat: sessions resource

---

prisma/schema.prisma

[Node SDK schema change](https://github.com/Salable/node-sdk/pull/135)
[Api schema change](https://bitbucket.org/adaptavistlabs/salable-api/pull-requests/600)

feat: added none to PaymentIntegration in schema

---

package-lock.json
prisma/schema.prisma
src/subscriptions/v2/subscriptions-v2.test.ts
src/types.ts

feat: subscription owner nullable

---

docs/docs/plans/get-checkout-link.md
docs/docs/subscriptions/get-all.md
docs/docs/subscriptions/update.md
package-lock.json
prisma/schema.prisma
src/subscriptions/index.ts
src/subscriptions/v2/index.ts
src/subscriptions/v2/subscriptions-v2.test.ts
src/types.ts

feat: subscription owner on getAll and update subscription

---

docs/docs/subscriptions/manage-seats.md
src/licenses/index.ts
src/licenses/v2/licenses-v2.test.ts
src/subscriptions/index.ts
src/subscriptions/v2/index.ts
src/subscriptions/v2/subscriptions-v2.test.ts
src/types.ts

feat: new subscriptions manageSeats method

---

prisma/schema.prisma

feat: add archived columns to product and plan

---

src/licenses/v2/licenses-v2.test.ts
src/plans/v2/plan-v2.test.ts
src/products/v2/product-v2.test.ts
src/subscriptions/v2/subscriptions-v2.test.ts
src/types.ts

- 
- Fixes the failing tests after adding `archivedAt` to the API

test: fix failing tests for archivedAt

---

src/types.ts

fix: pricing table plans type

---

src/types.ts

fix: product pricing table plans type

---

src/types.ts

fix: pricing table plan type fix
